version: "3.3"

services:
  amms_exmpl_text_clf:
    image: model_server:latest
    configs:
      - source: amms_model_config
        target: /app/data/config
        mode: 0440  # user and group are allowed to read
    volumes:
      - shared_volume:/shared_volume
    ports:
      - "5000:5000"
  retrain_exmpl_text_clf:
    image: retrain:latest
    env_file:
      - retrain/.retrain_env
    ports:
      - "6000:6000"
    volumes:
      - shared_volume:/shared_volume

configs:
  amms_model_config:
    file: amms/servables.json

volumes:
  shared_volume:


