version: "3.3"

services:
  amms_exmpl_text_clf:
    build: ../../amms
    configs:
      - source: amms_model_config
        target: /app/data/
        mode: 0440  # user and group are allowed to read
    volumes:
      - type: volume
        source: shared_volume
        target: /shared_volume
    ports:
      - "5000:5000"
  retrain_exmpl_text_clf:
    build: retrain
    env_file:
      - retrain/.retrain_env
    ports:
      - "6000:6000"

configs:
  amms_model_config:
    file: servables.json

volumes:
  shared_volume: